language: go

go:
  - 1.7.3

install:
  - go get github.com/mitchellh/gox
  - go get github.com/Masterminds/glide

script:
  - glide install
  - gox -os="darwin linux" -arch="amd64"

deploy:
  provider: releases
  api_key:
    secure: NZ/QOEiEjN50/uOHvSpRGG46WmcVlXOlipYU5mawfnFSJnl/DcBw+y0dBhvZPTDfQ/OSTwsxyhwnLc5brfokMZtQzp97ijS6poNwsjRz1uZ7QveBABFk/Z20tFo0vNx5r80cxnuFpTtLf0D0Jy50zXIMrAsXC5vPOpSbmBPDkIcA7poJHhupLpn7Mqogih7o+SlnFJ3QE8OUWSSMgo4Q1b/lRQRgrlqZrs0tyWUQCJN48rZVaDQ/+2YQG/Js5J/5vHoAUASNIoujadxpMVNqmq2CtF53n9CgA3eoWYMvg7UG30L0/QDNWqFn35fHYAXV8Y+Obtab+YGLsaII2BF4kvRrPyX4yIgTyzc9nUZQPIVh1yWcaVUhzPU+QgLEY0zfxqf5+5szMSpSwycu41zaOwWQAn5M4eZVHgWMzmhEg0rKoRPF/NCkquVOnwK1BXomNbV3t1F3qPHQPHgJHbYzorRA7l58FqF4b9NOfb9UjM3aGheH7PWFJ/TnMIfgOwp5nkQFXLJ0Ysqqmre2FiM+XUlHDmpBLZzBU9hy08+csSczixcjgXYQ2Oxa/RxwhZR4bh0/c9CW1Iew2krvBMLDHtUVqrW8o2SrVCQ9l5jY0KphmL+wZC8uMIDdnP0F/vhlj0tAirbT8cPrGEdbgKccAs/qQD7rvGW3evfC95RF1tM=
  file:
    - "qrpwd_darwin_amd64"
    - "qrpwd_linux_amd64"
  skip_cleanup: true
  on:
    tags: true
